### ISSUE TITLE
Getting submodules commad doesn't work

### ISSUE THREAD

**Issue by thatsnoi** [DavidGillsjo/polygon-HGT#1]
**How to reproduce:** `Run git clone --recurse-submodules git@github.com:DavidGillsjo/polygon-HGT.git` or `git clone git@github.com:DavidGillsjo/polygon-HGT.git
git submodule init
git submodule update` as described in the docs

**Expected behaviour:** Repo and submodules are cloned into directory

**Actual behaviour:** command fails: `Cloning into 'polygon-HGT'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.`

**Comment by DavidGillsjo** [comment]
Hi,

The commands assumes you have SSH keys setup for github.
If you want to use https you can modify the command to
```
git clone --recurse-submodules git@github.com:DavidGillsjo/polygon-HGT.git 
```
or 
```
git clone https://github.com:DavidGillsjo/polygon-HGT.git git submodule init git submodule update
```
