### ISSUE TITLE
problem with annotation and inference scripts

### ISSUE THREAD

**Issue by LucBourrat1** [DavidGillsjo/polygon-HGT#5]
I have a problem when trying to annotate data using the script structured3Dplanes_simple.py, the following modules are not found:

- structured3D_geometry
- Structured3D2wireframe

Where are these modules?

Also I tried running the inference script on my own images using these commands:
`cd scripts
python3 test.py \
--config-file ../config-files/Pred-simple-plane-S3D-GNN.yaml \
--img-folder <my-image-folder> \
CHECKPOINT ../data/model_polygon_hgt_joint.pth`

But it does not work because in yaml configuration file some path are not found.

Thanks for your help

**Comment by DavidGillsjo** [comment]
Sorry about that!
I've uploaded the missing files. Please reopen the issue if it doesn't work.
